version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore(deps)
    cooldown:
      default-days: 0

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore(ci)

  - package-ecosystem: "docker-compose"
    directory: "_docker-compose"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 0
