sonar.projectKey=sflotron_youtrack-provider
sonar.projectName=youtrack-provider
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=**/*_test.go,**/.git/**,**/.github/**,**/docs/**,**/examples/**,**/dev-environment/**,**/tools/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=coverage.xml
